---
   - name: Setup Server
     hosts: dev-ans-server
     become: true

     tasks:
     - name: Check Connection
       ping: 

     - name: Install Docker
       yum: 
        name: docker
        state: present
     
     - name: Ensure docker is running
       service: 
        name: docker 
        state: started
        enabled: yes          
       
     - name: install git
       yum:
         name: git
         state: present
                         
                              
     - name: Install docker-compose         
         get_url:
            url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
            dest: /usr/local/bin/docker-compose
            owner: "ansman"
            group: "ansman"
            mode: 'u+x,g+x'
         
     
     - name: Add user to group Docker        
        user:
          name: ansman
          shell: /bin/bash
          groups: docker
          append: yes